// flow-typed signature: 2ffb2b143264e9c9f4e7dc1c1269d6da
// flow-typed version: <<STUB>>/rollup-plugin-sourcemaps_v^0.6.3/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-sourcemaps/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-sourcemaps/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-sourcemaps/dist'>;
}
declare module 'rollup-plugin-sourcemaps/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-sourcemaps/dist'>;
}
