// flow-typed signature: 2351930bf2066c4c78354fa5e926d787
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.21.8/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
