// flow-typed signature: 9d3f94ea4c4e35b60801a3421c00e8b5
// flow-typed version: <<STUB>>/@rollup/plugin-replace_v^5.0.2/flow_v0.206.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-replace/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/plugin-replace/dist/es' {
  declare module.exports: any;
}

declare module '@rollup/plugin-replace/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-replace/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/plugin-replace/dist/cjs'>;
}
declare module '@rollup/plugin-replace/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-replace/dist/cjs'>;
}
declare module '@rollup/plugin-replace/dist/es/index' {
  declare module.exports: $Exports<'@rollup/plugin-replace/dist/es'>;
}
declare module '@rollup/plugin-replace/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-replace/dist/es'>;
}
declare module '@rollup/plugin-replace/src/index' {
  declare module.exports: $Exports<'@rollup/plugin-replace/src'>;
}
declare module '@rollup/plugin-replace/src/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-replace/src'>;
}
